# Site
name: "Islam Talk"
title: "Islam Talk"
description: "Pray For Your Heart"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
# google_analytics: 'UA-xxxxxxxx-1'
disqus: 'islamtalk'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: sirmegamu@outlook.com

# Authors
authors:
  jia:
    name: 佳
    display_name: 佳
    avatar: 'assets/images/avatar-jia.png'
    # email: wowthemesnet@gmail.com
    # web: https://www.wowthemes.net/donate/
    # twitter: https://twitter.com/wowthemesnet
    description: "Author"
  MegaMU:
    name: MegaMU
    display_name: MegaMU
    avatar: 'assets/images/avatar-megamu.png'
    email: sirmegamu@outlook.com
    web: https://megamu.icu/
    description: "Site Builder"
  wenqin:
    name: 问琴
    display_name: 问琴
    avatar: 'assets/images/avatar-wenqin.png'
    email: 1107874930@qq.com
    description: "Auther"



# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
